#######
#

# set target & soruce file

TARGET1    = MapSearch
SRC1       = MapSearch.c

TARGETS = $(TARGET1)

##########
# The rule is set. 
all:	$(TARGETS)

$(TARGET1): $(SRC1)
	gcc -Wall -o $@ $<

clean:
	rm $(TARGETS)


